#name, main, version and api are required
name: iZone
main: iZone\iZone
version: 2.0.0
api: [1.12.0]

load: POSTWORLD
author: InusualZ
description: Protect Multiple Zone
website:
commands:
 izone:
  description: iZone Command
  usage: "/izone <command> [parameters...] {optional...}"
  permission: izone.command.izone
permissions:
 izone.command.izone:
  description: "Allows the user to run the izone's command"
  default: true